config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'users#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'login#index', as: :unauthenticated_root
    end
  end

  get '/login', to: 'login#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post
    namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          get 'comments', to: 'comments#comments_for_post'
        end
      end
      root 'users#index'
    end
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :post
  after_save :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @like = Like.new(post_id: params[:post_id], user_id: params[:user_id])
    @like.user = current_user
    if @like.save
      flash[:success] = 'Liked !'
      redirect_to user_post_path(id: @like.post_id, user_id: @like.user_id)
    else
      flash.now[:error] = 'Something went wrong!'
    end
  end
end

app/views/likes/_like_action.html.erb
<%# <% if post.likes.indlude?(current_user.id) %>
<%= form_with model: @like, url: user_post_likes_path(post_id: post.id, user_id: post.author_id), data: { turbo: false }, local: true, scope: :like do |f| %>
  <div>
    <%= f.hidden_field :user_id, value: :user_id %>
    <%= f.hidden_field :post_id, value: :post_id %>
    <%= f.submit "Like post", class: 'btn btn-primary' %>
  </div>
<% end %>