config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'users#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'login#index', as: :unauthenticated_root
    end
  end

  get '/login', to: 'login#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post
    namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          get 'comments', to: 'comments#comments_for_post'
        end
      end
      root 'users#index'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments
  has_many :likes

  def three_most_recent_posts
    Post.where(author_id: self).order(created_at: :desc).limit(3)
  end

  # Add validations

  # Name must not be blank.
  validates :name, presence: true

  # PostsCounter must be an integer greater than or equal to zero.
  validates :posts_counter, numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 0 }

  def admin?
    role == 'admin'
  end
end

# <%= render 'posts/all_posts' %>

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  layout 'standard'
  def index
    @users = User.all
    render json: @users, status: :ok, only: %i[id name]
  end

  def show
    @user = User.find(params[:id])
    render json: @user, status: :ok, only: %i[id name bio photo]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/api/v1/users_helper.rb
module Api::V1::UsersHelper
end

app/views/users/_user_info.html.erb
<div class="user-photo",>
  <%= image_tag(user.photo || "missing_avatar.png", alt: "a_user") %>
</div>

<div class="user-text">
  <h2><%= user.name %></h2><br>
  <p>Number of posts: <%= user.posts_counter.to_i %></p>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>

<div class="my-3 rounded border border-1">
  <div class="card">
    <div class="row g-0">
      <div class="col-md-2">
        <img src="<%= user.photo %>" class="img-fluid rounded-start" />
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h1 class="card-title"><%= link_to user.name, user_path(user.id), class: 'text-black link-underline link-underline-opacity-0' %></h1>
          <div class="text-end">
            <p>
              Number of posts: <%= user.posts_counter.nil? ? "0" : user.posts_counter %>
            </p>
          </div>
            <%= link_to "User info", user_path(user.id), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/users/show.html.erb
<div>
  <div class="card g-0 my-4">
    
    <div class="row align-items-center">
      <div class="col-md-2">
        <img src="<%= @user.photo %>" class="img-fluid rounded-start" />
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h1 class="card-title"><%= @user.name %></h1>
          <p class="text-end">
            Number of posts: <%= @user.posts_counter.nil? ? "0" : @user.posts_counter %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <div class="my-4 p-4 rounded border border-1">
    <h4>Bio</h4>
    <p><%= @user.bio %></p>
  </div>

  <% @user.three_most_recent_posts.each do |recent| %>
  <div class="rounded p-4 border border-1 my-4">
    <h4><%= recent.title %></h4>
    <p><%= recent.text %></p>
    <div class="text-end">
        <span class="border border-1 p-1 me-4 bg-info">
          Comments: <%= recent.comments_counter.nil? ? " 0 " : recent.comments_counter %>
        </span>
        <span class="border border-1 p-1 bg-info">
          Likes: <%= recent.likes_counter.nil? ? "0" : recent.likes_counter %>
        </span>
    </div>
    <%= link_to "Read Post", user_post_path(@user.id, recent), class: "btn btn-primary" %>
  </div>
  <% end %>
  <div class="d-flex justify-content-center my-4">
    <%= link_to "See all post", user_posts_path(@user.id), class: "btn btn-primary" %>
  </div>
</div>