config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root :to => 'users#index', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'login#index', as: :unauthenticated_root
    end
  end

  get '/login', to: 'login#index'
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end
  end
  
  delete 'posts/:id', to: 'posts#destroy', as: :destroy_post
    namespace :api do
    namespace :v1 do
      resources :users do
        resources :posts do
          get 'comments', to: 'comments#comments_for_post'
        end
      end
      root 'users#index'
    end
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy, foreign_key: :post_id
  has_many :likes, dependent: :destroy, foreign_key: :post_id
  after_create :update_post_counter
  after_destroy :update_post_counter
  after_save :update_post_counter

  def five_recent_comments
    Comment.where(post_id: id).order(created_at: :desc).limit(5)
  end

  def update_post_counter
    author.increment!(:posts_counter)
  end

  def all_comments
    Comment.where(post_id: id)
  end

  # Add validations

  # Title must not be blank.
  validates :title, presence: true

  # Title must not exceed 250 characters.
  validates :title, length: { maximum: 250 }

  # CommentsCounter must be an integer greater than or equal to zero.
  validates :comments_counter, numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 0 }

  # LikesCounter must be an integer greater than or equal to zero.
  validates :likes_counter, numericality: { allow_nil: true, only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  layout 'standard'

  load_and_authorize_resource
  rescue_from CanCan::AccessDenied do |_exception|
    redirect_to root_path, notice: 'Access Denied!'
  end

  def index
    @user = User.includes(:posts).find(params[:user_id])
    @posts = Post.where(author: @user)
    render json: @posts, status: :ok, only: %i[id author_id title text]
  end

  def show
    @comments = Comment.where(post: @post.id)
    render json: @post.comments, status: :ok, only: %i[id author_id post_id text]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :load_and_authorize_resource
  def index
    @user = User.find(params[:user_id])
    # retrieve posts associated to @user and
    # eager-loading the associated comments
    @posts = @user.posts.includes(comments: [:user])
  rescue ActiveRecord::RecordNotFound
    # Handle the case where the user is not found
    # Redirect to the root page
    flash[:error] = 'User not found.'
    redirect_to root_path
  end

  def show
    @user = User.find(params[:user_id])
    # retrieve the post associated to @user and
    # eager-loading the associated comments
    @post = @user.posts.includes(:comments).find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(params.require(:post).permit(:title, :text))
    @post.author = current_user
    if @post.save
      flash[:success] = 'Post created successfully!'
      redirect_to user_posts_url
    else
      flash.now[:error] = 'Error: Post could not be created!'
      render :new, locals: { post: @post }
    end
  end

  private

  def load_and_authorize_resource
    # Load and authorize resources as needed
  end
end

app/helpers/api/v1/posts_helper.rb
module Api::V1::PostsHelper
end

app/views/posts/_all_posts.html.erb
<%= @comments_and_likes_counter %>
<% Post.all.each do |post| %>
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <p>Comments: <%= post.comments_counter.nil? ? "0" : post.comments_counter %> </p>
    <p>Likes: <%= post.likes_counter.nil? ? "0" : post.likes_counter %> </p>
    <a class="btn btn-primary"href="/users/<%= post.author_id %>/posts/<%= post.id %>">Read post</a>
<% end %>

app/views/posts/_post_info.html.erb
<h3><%= post.title %></h3>

<p><%= truncate(post.text, length: 100, omission: '...') %></p>

<% if can? :destroy, post %>
    <%= button_to 'Delete post', destroy_post_path(post), method: :delete, class:"btn-delete" %>
<% end %>

<p class="counter">
  Comments: <%= post.comments_counter.to_i %>, Likes: <%= post.likes_counter.to_i %>
</p>

app/views/posts/index.html.erb
<% user = User.find(params[:user_id]) %>
  <div class="card g-0 my-4">
    
    <div class="row align-items-center">
      <div class="col-md-2">
        <img src="<%= user.photo %>" class="img-fluid rounded-start" />
      </div>
      <div class="col-md-10">
        <div class="card-body">
          <h1 class="card-title"><%= user.name %></h1>
          <p class="text-end">
            Number of posts: <%= user.posts_counter.nil? ? "0" : user.posts_counter %>
          </p>
        </div>
      </div>
    </div>
  </div>
  <%= link_to 'New Post', new_user_post_path, class: 'btn btn-primary'%>
  <div class="text-success">
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
  </div>
<% @posts.each do |post| %>
  <div class="rounded p-4 border border-1 my-4">
    
    <h3><%= post.title %></h3>
    <p><%= post.text %></p>
    <div class="text-end">
        <span class="border border-1 p-1 me-4 bg-info">
          Comments: <%= post.comments_counter.nil? ? " 0 " : post.comments_counter %>
        </span>
        <span class="border border-1 p-1 bg-info">
          Likes: <%= post.likes_counter.nil? ? "0" : post.likes_counter %>
        </span>
    </div>
    <%= link_to "Read Post", user_post_path(user_id: post.author_id, id: post.id), class: "btn btn-primary" %>
    </div>
    <div class="mb-4">
      <% post.five_recent_comments.each do |comment| %>
        <p><% if comment.nil? %>
        <%= "This post has no comment" %> 
          <% else %>
          <h4>Comments </h4>
          <%= comment.user.name %>: <%= comment.text %>
          <% end %>
        </p>
      <% end %>
    </div>
<% end %>
<div class="d-flex justify-content-center my-4">
  <%= link_to "Pagination", user_posts_path(user_id: user.id), class: "btn btn-primary mx-auto text-center" %>
</div>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<%= form_with model: [:user, @post], data: { turbo: false }, local: true do |f| %>
  <div class="form-group col-6">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %><br>
    <%= f.label :text %><br>
    <%= f.text_area :text, class: 'form-control' %><br>
    <%= f.submit "Create Post", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/posts/show.html.erb
<% user = User.find(params[:user_id]) %>

<div class="my-4 p-5 rounded border border-1">
  <div class="d-flex align-items-center justify-content-between">
    <h3><%= @post.title %> by <%= user.name %></h3>
    <div class="text-end">
      <span class="border border-1 p-1 me-4 bg-info">
        Comments: <%= @post.comments_counter.nil? ? " 0 " :
        @post.comments_counter %>
      </span>
      <span class="border border-1 p-1 bg-info">
        Likes: <%= @post.likes_counter.nil? ? "0" : @post.likes_counter %>
      </span>
    </div>
  </div>
  <hr>
  <p class="pt-5"><%= @post.text %></p>
</div>

<div class="text-success">
  <% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
  <% end -%>
</div>

<div class="border border-1 p-2">
  <% @post.all_comments.each do |post| %>
    <p><%= post.nil? ? "No comment" : user.name + " : " + post.text %></p>
  <% end %>
</div>

  <% @post.comments.each do |comment| %>
    <p>
      <%= comment.author.name %>: <%= comment.text %>
    </p>
    <% if can? :destroy, comment %>
      <%= button_to 'Delete', post_comment_path(@post, comment),  class:"btn-delete btn-del-comment" , method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  <% end %>

<div class="d-flex my-2">
  <%= render partial: "likes/like_action", locals: { post: @post }, class: 'mx-4' %>
  <%= link_to 'New Comment', new_user_post_comment_path(post_id: params[:id]), class: "mx-4 btn btn-primary" %>
</div>